# Generated by Django 2.0.5 on 2018-07-30 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180730_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='cc_id_load',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flow_cc_id_load', to='app.Contact'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='cc_id_pub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flow_cc_id_pub', to='app.Contact'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='fissure_id',
            field=models.ForeignKey(db_column='flow.fissure_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flow_fissure_id', to='app.Fissure'),
        ),
    ]
