# Generated by Django 2.0.5 on 2018-07-30 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180730_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='fissure_id',
            field=models.ForeignKey(db_column='fissure_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flow_fissure_id', to='app.Fissure'),
        ),
    ]
