# Generated by Django 2.0.5 on 2018-07-31 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180730_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='fissure_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flow_fissure_id', to='app.Fissure'),
        ),
    ]
