# Generated by Django 2.0.5 on 2018-07-31 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180731_0556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flow',
            old_name='cc_id_load',
            new_name='cc_load',
        ),
    ]
