# Generated by Django 2.0.5 on 2018-07-31 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180731_0600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flow',
            name='cc_id_load',
        ),
        migrations.RemoveField(
            model_name='flow',
            name='cc_id_pub',
        ),
        migrations.AddField(
            model_name='flow',
            name='cc_load',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flow_cc_load_id', to='app.Contact'),
        ),
        migrations.AddField(
            model_name='flow',
            name='cc_pub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flow_cc_pub_id', to='app.Contact'),
        ),
    ]
