# Generated by Django 2.0.5 on 2018-08-09 08:54

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180731_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=32740),
        ),
    ]
