# Generated by Django 2.0.5 on 2018-08-10 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180809_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acquisitionmethod',
            old_name='cs_id',
            new_name='cs',
        ),
        migrations.RenameField(
            model_name='composition',
            old_name='cone_id',
            new_name='cone',
        ),
        migrations.RenameField(
            model_name='composition',
            old_name='flow_id',
            new_name='flow',
        ),
        migrations.RenameField(
            model_name='composition',
            old_name='teph_id',
            new_name='teph',
        ),
        migrations.RenameField(
            model_name='cone',
            old_name='fissure_id',
            new_name='fissure',
        ),
        migrations.RenameField(
            model_name='eruption',
            old_name='vd_id',
            new_name='vd',
        ),
        migrations.RenameField(
            model_name='fissure',
            old_name='ed_id',
            new_name='ed',
        ),
        migrations.RenameField(
            model_name='mntortho',
            old_name='am_id',
            new_name='am',
        ),
        migrations.RenameField(
            model_name='petrology',
            old_name='cone_id',
            new_name='cone',
        ),
        migrations.RenameField(
            model_name='petrology',
            old_name='flow_id',
            new_name='flow',
        ),
        migrations.RenameField(
            model_name='petrology',
            old_name='teph_id',
            new_name='teph',
        ),
        migrations.RenameField(
            model_name='tephras',
            old_name='fissure_id',
            new_name='fissure',
        ),
        migrations.RenameField(
            model_name='volcanoinformation',
            old_name='cc_id',
            new_name='cc',
        ),
        migrations.RenameField(
            model_name='volcanoinformation',
            old_name='vd_id',
            new_name='vd',
        ),
        migrations.RenameField(
            model_name='volume',
            old_name='cone_id',
            new_name='cone',
        ),
        migrations.RenameField(
            model_name='volume',
            old_name='flow_id',
            new_name='flow',
        ),
        migrations.RenameField(
            model_name='volume',
            old_name='teph_id',
            new_name='teph',
        ),
        migrations.RemoveField(
            model_name='acquisitionmethod',
            name='cc_id_load',
        ),
        migrations.RemoveField(
            model_name='acquisitionmethod',
            name='cc_id_pub',
        ),
        migrations.RemoveField(
            model_name='acquisitiontool',
            name='cc_id_load',
        ),
        migrations.RemoveField(
            model_name='acquisitiontool',
            name='cc_id_pub',
        ),
        migrations.RemoveField(
            model_name='bibliographic',
            name='cc_id_load',
        ),
        migrations.RemoveField(
            model_name='composition',
            name='cc_id_load',
        ),
        migrations.RemoveField(
            model_name='composition',
            name='cc_id_pub',
        ),
        migrations.RemoveField(
            model_name='cone',
            name='cc_id_load',
        ),
        migrations.RemoveField(
            model_name='cone',
            name='cc_id_pub',
        ),
        migrations.RemoveField(
            model_name='eruption',
            name='cc_id_load',
        ),
        migrations.RemoveField(
            model_name='fissure',
            name='cc_id_load',
        ),
        migrations.RemoveField(
            model_name='fissure',
            name='cc_id_pub',
        ),
        migrations.RemoveField(
            model_name='mntortho',
            name='cc_id_load',
        ),
        migrations.RemoveField(
            model_name='mntortho',
            name='cc_id_pub',
        ),
        migrations.RemoveField(
            model_name='petrology',
            name='cc_id_load',
        ),
        migrations.RemoveField(
            model_name='petrology',
            name='cc_id_pub',
        ),
        migrations.RemoveField(
            model_name='satelliteairplane',
            name='cc_id_load',
        ),
        migrations.RemoveField(
            model_name='satelliteairplane',
            name='cc_id_pub',
        ),
        migrations.RemoveField(
            model_name='tephras',
            name='cc_id_load',
        ),
        migrations.RemoveField(
            model_name='tephras',
            name='cc_id_pub',
        ),
        migrations.RemoveField(
            model_name='volcano',
            name='cc_id_load',
        ),
        migrations.RemoveField(
            model_name='volcanoinformation',
            name='cc_id_load',
        ),
        migrations.RemoveField(
            model_name='volume',
            name='cc_id_load',
        ),
        migrations.RemoveField(
            model_name='volume',
            name='cc_id_pub',
        ),
        migrations.AddField(
            model_name='acquisitionmethod',
            name='cc_load',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='am_cc_load_id', to='app.Contact'),
        ),
        migrations.AddField(
            model_name='acquisitionmethod',
            name='cc_pub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='am_cc_pub_id', to='app.Contact'),
        ),
        migrations.AddField(
            model_name='acquisitiontool',
            name='cc_load',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='at_cc_load_id', to='app.Contact'),
        ),
        migrations.AddField(
            model_name='acquisitiontool',
            name='cc_pub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='at_cc_pub_id', to='app.Contact'),
        ),
        migrations.AddField(
            model_name='bibliographic',
            name='cc_load',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cb_cc_load_id', to='app.Contact'),
        ),
        migrations.AddField(
            model_name='composition',
            name='cc_load',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compo_cc_load_id', to='app.Contact'),
        ),
        migrations.AddField(
            model_name='composition',
            name='cc_pub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compo_cc_pub_id', to='app.Contact'),
        ),
        migrations.AddField(
            model_name='cone',
            name='cc_load',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cone_cc_load_id', to='app.Contact'),
        ),
        migrations.AddField(
            model_name='cone',
            name='cc_pub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cone_cc_pub_id', to='app.Contact'),
        ),
        migrations.AddField(
            model_name='eruption',
            name='cc_load_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ed_cc_load_id', to='app.Contact'),
        ),
        migrations.AddField(
            model_name='fissure',
            name='cc_load',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fissure_cc_load_id', to='app.Contact'),
        ),
        migrations.AddField(
            model_name='fissure',
            name='cc_pub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fissure_cc_pub_id', to='app.Contact'),
        ),
        migrations.AddField(
            model_name='mntortho',
            name='cc_load',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mo_cc_load_id', to='app.Contact'),
        ),
        migrations.AddField(
            model_name='mntortho',
            name='cc_pub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mo_cc_pub_id', to='app.Contact'),
        ),
        migrations.AddField(
            model_name='petrology',
            name='cc_load',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='petro_cc_load_id', to='app.Contact'),
        ),
        migrations.AddField(
            model_name='petrology',
            name='cc_pub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='petro_cc_pub_id', to='app.Contact'),
        ),
        migrations.AddField(
            model_name='satelliteairplane',
            name='cc_load',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cs_cc_load_id', to='app.Contact'),
        ),
        migrations.AddField(
            model_name='satelliteairplane',
            name='cc_pub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cs_cc_pub_id', to='app.Contact'),
        ),
        migrations.AddField(
            model_name='tephras',
            name='cc_load',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teph_cc_load_id', to='app.Contact'),
        ),
        migrations.AddField(
            model_name='tephras',
            name='cc_pub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teph_cc_pub_id', to='app.Contact'),
        ),
        migrations.AddField(
            model_name='volcano',
            name='cc_load',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vd_cc_load_id', to='app.Contact'),
        ),
        migrations.AddField(
            model_name='volcanoinformation',
            name='cc_load',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vd_inf_cc_load_id', to='app.Contact'),
        ),
        migrations.AddField(
            model_name='volume',
            name='cc_load',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volume_cc_load_id', to='app.Contact'),
        ),
        migrations.AddField(
            model_name='volume',
            name='cc_pub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volume_cc_pub_id', to='app.Contact'),
        ),
    ]
