# Generated by Django 2.0.5 on 2018-08-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20180810_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fissure',
            name='com',
            field=models.CharField(max_length=255, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='fissure',
            name='loaddate',
            field=models.DateTimeField(null=True, verbose_name='Load date, the date the data was entered (in UTC)'),
        ),
        migrations.AlterField(
            model_name='fissure',
            name='opentime',
            field=models.DateTimeField(null=True, verbose_name='Open time'),
        ),
        migrations.AlterField(
            model_name='fissure',
            name='opentime_bc',
            field=models.IntegerField(null=True, verbose_name='Year of open time before Christ'),
        ),
        migrations.AlterField(
            model_name='fissure',
            name='opentime_unc',
            field=models.DateTimeField(null=True, verbose_name='Open time uncertainty'),
        ),
        migrations.AlterField(
            model_name='fissure',
            name='pubdate',
            field=models.DateTimeField(null=True, verbose_name='Publish date, the date the data become public'),
        ),
    ]
