# Generated by Django 2.0.5 on 2018-08-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20180810_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='fissure',
            name='com2',
            field=models.CharField(max_length=255, null=True, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='fissure',
            name='com3',
            field=models.CharField(max_length=255, null=True, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='fissure',
            name='com4',
            field=models.CharField(max_length=255, null=True, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='fissure',
            name='com5',
            field=models.CharField(max_length=255, null=True, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='fissure',
            name='com6',
            field=models.CharField(max_length=255, null=True, verbose_name='Comments'),
        ),
    ]
