# Generated by Django 2.0.5 on 2018-08-13 05:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20180810_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='mntortho',
            name='raster',
            field=django.contrib.gis.db.models.fields.RasterField(null=True, srid=32740),
        ),
        migrations.AlterField(
            model_name='mntortho',
            name='com',
            field=models.CharField(blank=True, max_length=255, verbose_name='Comments'),
        ),
    ]
