# Generated by Django 2.0.5 on 2018-08-13 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20180813_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mntortho',
            name='cb_ids',
            field=models.ManyToManyField(null=True, to='app.Bibliographic'),
        ),
        migrations.AlterField(
            model_name='mntortho',
            name='com',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='mntortho',
            name='flow_ids',
            field=models.ManyToManyField(null=True, to='app.Flow'),
        ),
        migrations.AlterField(
            model_name='mntortho',
            name='gcp_num',
            field=models.IntegerField(null=True, verbose_name='Gcp number'),
        ),
        migrations.AlterField(
            model_name='mntortho',
            name='loaddate',
            field=models.DateTimeField(null=True, verbose_name='Load date, the date the data was entered (in UTC)'),
        ),
        migrations.AlterField(
            model_name='mntortho',
            name='mo_gcp_type',
            field=models.CharField(choices=[('GNSSM', 'GNSS measure'), ('RIMAG', 'Replicated image')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='mntortho',
            name='mo_software',
            field=models.CharField(choices=[('PHOTO', 'PhotoScan'), ('MICMA', 'MicMac'), ('ERDAS', 'ERDAS'), ('ARCVI', 'ArcView'), ('POIVI', 'Poivillier'), ('ENVI', 'Envi'), ('GLOBM', 'Global Mapper'), ('CLOUD', 'Cloud Compare')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='mntortho',
            name='mo_type',
            field=models.CharField(choices=[('MNT', 'Mnt'), ('ORTHO', 'Orthophoto')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='mntortho',
            name='precision',
            field=models.FloatField(null=True, verbose_name='Accuracy of the reference altitude'),
        ),
        migrations.AlterField(
            model_name='mntortho',
            name='pubdate',
            field=models.DateTimeField(null=True, verbose_name='Publish date, the date the data become public'),
        ),
        migrations.AlterField(
            model_name='mntortho',
            name='reference_altitude',
            field=models.FloatField(null=True, verbose_name='Reference altitude'),
        ),
    ]
