# Generated by Django 2.0.5 on 2018-08-13 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20180813_0539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mntortho',
            old_name='raster',
            new_name='geometry',
        ),
    ]
