# Generated by Django 2.0.5 on 2018-08-14 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20180813_0647'),
    ]

    operations = [
        migrations.CreateModel(
            name='EruptionObservation',
            fields=[
                ('eo_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID, Eruption Observation identifier')),
                ('eo_code', models.CharField(max_length=30, null=True, verbose_name='Observation code')),
                ('eo_observe', models.TextField(verbose_name='Description')),
                ('eo_stime', models.DateTimeField(verbose_name='Start time')),
                ('eo_stime_unc', models.DateTimeField(verbose_name='Start time uncertainty')),
                ('eo_etime', models.DateTimeField(verbose_name='End time')),
                ('eo_etime_unc', models.DateTimeField(verbose_name='End time uncertainty')),
                ('eo_com', models.CharField(max_length=255, verbose_name='Comments')),
                ('eo_loaddate', models.DateTimeField(verbose_name='Load date, the date the data was entered (in UTC)')),
                ('eo_pubdate', models.DateTimeField(verbose_name='Publish date, the date the data become public')),
                ('cb_ids', models.ManyToManyField(to='app.Bibliographic')),
                ('cc_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eo_cc_id', to='app.Contact')),
                ('cc_id2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eo_cc_id2', to='app.Contact')),
                ('cc_id3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eo_cc_id3', to='app.Contact')),
                ('cc_id4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eo_cc_id4', to='app.Contact')),
                ('cc_id5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eo_cc_id5', to='app.Contact')),
                ('cc_load', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eo_cc_load_id', to='app.Contact')),
                ('ed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eo_ed_id', to='app.Eruption')),
            ],
            options={
                'db_table': 'eo',
            },
        ),
        migrations.CreateModel(
            name='SeismicEvent',
            fields=[
                ('sd_ev_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID, Seismic event identifier (index)')),
                ('sd_ev_code', models.CharField(max_length=30, verbose_name='Seismic event code')),
                ('sd_ev_stime', models.DateTimeField(verbose_name='Start time')),
                ('sd_ev_stime_bc', models.IntegerField(verbose_name='Year of start time before Christ')),
                ('sd_ev_stime_unc', models.DateTimeField(verbose_name='Start time uncertainty')),
                ('sd_ev_etime', models.DateTimeField(verbose_name='End time')),
                ('sd_ev_etime_bc', models.IntegerField(verbose_name='Year of end time before Christ')),
                ('sd_ev_etime_unc', models.DateTimeField(verbose_name='End time uncertainty')),
                ('sd_ev_com', models.CharField(max_length=255, verbose_name='Comments')),
                ('sd_ev_loaddate', models.DateTimeField(verbose_name='Load date, the date the data was entered (in UTC)')),
                ('sd_ev_pubdate', models.DateTimeField(verbose_name='Publish date, the date the data become public')),
                ('cb_ids', models.ManyToManyField(to='app.Bibliographic')),
                ('cc_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sd_ev_cc_id', to='app.Contact')),
                ('cc_id2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sd_ev_cc_id2', to='app.Contact')),
                ('cc_id3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sd_ev_cc_id3', to='app.Contact')),
                ('cc_load_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sd_ev_cc_load_id', to='app.Contact')),
                ('ed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sd_ev_ed_id', to='app.Eruption')),
            ],
            options={
                'db_table': 'sd_ev',
            },
        ),
        migrations.RenameField(
            model_name='observation',
            old_name='vd_id',
            new_name='vd',
        ),
        migrations.RemoveField(
            model_name='composition',
            name='cone',
        ),
        migrations.RemoveField(
            model_name='composition',
            name='flow',
        ),
        migrations.RemoveField(
            model_name='composition',
            name='teph',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='cc_id_load',
        ),
        migrations.RemoveField(
            model_name='petrology',
            name='cone',
        ),
        migrations.RemoveField(
            model_name='petrology',
            name='flow',
        ),
        migrations.RemoveField(
            model_name='petrology',
            name='teph',
        ),
        migrations.AddField(
            model_name='composition',
            name='sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compo_sample_id', to='app.Sample'),
        ),
        migrations.AddField(
            model_name='flow',
            name='flux',
            field=models.FloatField(null=True, verbose_name='Flux'),
        ),
        migrations.AddField(
            model_name='observation',
            name='cc_load',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_cc_load_id', to='app.Contact'),
        ),
        migrations.AddField(
            model_name='petrology',
            name='sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='petro_sample_id', to='app.Sample'),
        ),
        migrations.AddField(
            model_name='sample',
            name='cc_load',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sample_cc_load_id', to='app.Contact'),
        ),
        migrations.AddField(
            model_name='sample',
            name='cc_pub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sample_cc_pub_id', to='app.Contact'),
        ),
        migrations.AddField(
            model_name='sample',
            name='cone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sample_cone_id', to='app.Cone'),
        ),
        migrations.AddField(
            model_name='sample',
            name='flow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sample_flow_id', to='app.Flow'),
        ),
        migrations.AddField(
            model_name='sample',
            name='teph',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sample_teph_id', to='app.Tephras'),
        ),
    ]
