# Generated by Django 2.0.5 on 2018-08-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20180814_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cone',
            old_name='time_bc',
            new_name='stime_bc',
        ),
        migrations.AddField(
            model_name='cone',
            name='com2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='cone',
            name='com',
            field=models.CharField(blank=True, max_length=255, verbose_name='Date comment'),
        ),
    ]
