# Generated by Django 2.0.5 on 2018-08-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20180816_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='cone',
            name='com3',
            field=models.CharField(blank=True, max_length=255, verbose_name='Author comments'),
        ),
        migrations.AlterField(
            model_name='cone',
            name='com2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Comments'),
        ),
    ]
