# Generated by Django 2.0.5 on 2018-08-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20180816_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cone',
            name='accretion_date',
            field=models.DateTimeField(null=True, verbose_name='Date of accretion'),
        ),
        migrations.AlterField(
            model_name='cone',
            name='accretion_date_bc',
            field=models.IntegerField(null=True, verbose_name='Year of accretion date before Christ'),
        ),
        migrations.AlterField(
            model_name='cone',
            name='accretion_date_unc',
            field=models.DateTimeField(null=True, verbose_name='Accretion date uncertainty'),
        ),
        migrations.AlterField(
            model_name='cone',
            name='cb_ids',
            field=models.ManyToManyField(null=True, to='app.Bibliographic'),
        ),
        migrations.AlterField(
            model_name='cone',
            name='com',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Date comment'),
        ),
        migrations.AlterField(
            model_name='cone',
            name='com2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='cone',
            name='com3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Author comments'),
        ),
        migrations.AlterField(
            model_name='cone',
            name='cone_type',
            field=models.CharField(choices=[('STRAT', 'Stratocone'), ('SPATT', 'Spatter cone'), ('TUFFC', 'Tuff cones'), ('CINDE', 'Cinder cone'), ('ROOTL', 'Rootless cones')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='cone',
            name='crater_diameter',
            field=models.FloatField(null=True, verbose_name='Crater diameter'),
        ),
        migrations.AlterField(
            model_name='cone',
            name='disappearance_date',
            field=models.DateTimeField(null=True, verbose_name='Date of disappearance'),
        ),
        migrations.AlterField(
            model_name='cone',
            name='disappearance_date_bc',
            field=models.IntegerField(null=True, verbose_name='Year of disappearance date before Christ'),
        ),
        migrations.AlterField(
            model_name='cone',
            name='disappearance_date_unc',
            field=models.DateTimeField(null=True, verbose_name='Disappearance date uncertainty'),
        ),
        migrations.AlterField(
            model_name='cone',
            name='height',
            field=models.FloatField(null=True, verbose_name='Height of the cone'),
        ),
        migrations.AlterField(
            model_name='cone',
            name='loaddate',
            field=models.DateTimeField(null=True, verbose_name='Load date, the date the data was entered (in UTC)'),
        ),
        migrations.AlterField(
            model_name='cone',
            name='name',
            field=models.CharField(max_length=60, null=True, verbose_name='ConeName'),
        ),
        migrations.AlterField(
            model_name='cone',
            name='pubdate',
            field=models.DateTimeField(null=True, verbose_name='Publish date, the date the data become public'),
        ),
        migrations.AlterField(
            model_name='cone',
            name='stime',
            field=models.DateTimeField(null=True, verbose_name='Start time'),
        ),
        migrations.AlterField(
            model_name='cone',
            name='stime_bc',
            field=models.IntegerField(null=True, verbose_name='Year of start time before Christ'),
        ),
        migrations.AlterField(
            model_name='cone',
            name='stime_unc',
            field=models.DateTimeField(null=True, verbose_name='Start time uncertainty'),
        ),
    ]
