# Generated by Django 2.0.5 on 2018-08-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20180816_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cone',
            name='cb_ids',
            field=models.ManyToManyField(to='app.Bibliographic'),
        ),
    ]
