# Generated by Django 2.0.5 on 2018-08-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20180821_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seismicevent',
            name='sd_ev_code',
            field=models.CharField(max_length=30, null=True, verbose_name='Seismic event code'),
        ),
        migrations.AlterField(
            model_name='seismicevent',
            name='sd_ev_com',
            field=models.CharField(max_length=255, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='seismicevent',
            name='sd_ev_etime',
            field=models.DateTimeField(null=True, verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='seismicevent',
            name='sd_ev_etime_bc',
            field=models.IntegerField(null=True, verbose_name='Year of end time before Christ'),
        ),
        migrations.AlterField(
            model_name='seismicevent',
            name='sd_ev_etime_unc',
            field=models.DateTimeField(null=True, verbose_name='End time uncertainty'),
        ),
        migrations.AlterField(
            model_name='seismicevent',
            name='sd_ev_loaddate',
            field=models.DateTimeField(null=True, verbose_name='Load date, the date the data was entered (in UTC)'),
        ),
        migrations.AlterField(
            model_name='seismicevent',
            name='sd_ev_pubdate',
            field=models.DateTimeField(null=True, verbose_name='Publish date, the date the data become public'),
        ),
        migrations.AlterField(
            model_name='seismicevent',
            name='sd_ev_stime',
            field=models.DateTimeField(null=True, verbose_name='Start time'),
        ),
        migrations.AlterField(
            model_name='seismicevent',
            name='sd_ev_stime_bc',
            field=models.IntegerField(null=True, verbose_name='Year of start time before Christ'),
        ),
        migrations.AlterField(
            model_name='seismicevent',
            name='sd_ev_stime_unc',
            field=models.DateTimeField(null=True, verbose_name='Start time uncertainty'),
        ),
    ]
