# Generated by Django 2.0.5 on 2018-08-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20180821_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volcano',
            name='vd_cavw',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='The current CAVW number'),
        ),
        migrations.AlterField(
            model_name='volcano',
            name='vd_com',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='volcano',
            name='vd_loaddate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Load date, the date the data was entered (in UTC)'),
        ),
        migrations.AlterField(
            model_name='volcano',
            name='vd_mcont',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='M=Multiple contacts for this volcano'),
        ),
        migrations.AlterField(
            model_name='volcano',
            name='vd_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Volcano Name (first)'),
        ),
        migrations.AlterField(
            model_name='volcano',
            name='vd_name2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Volcano Name (second)'),
        ),
        migrations.AlterField(
            model_name='volcano',
            name='vd_pubdate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Publish date, the date the data become public'),
        ),
        migrations.AlterField(
            model_name='volcano',
            name='vd_tzone',
            field=models.FloatField(blank=True, null=True, verbose_name='Time zone (relative to UTC)'),
        ),
    ]
