# Generated by Django 2.0.5 on 2018-08-23 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20180821_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cone',
            name='stime',
        ),
        migrations.RemoveField(
            model_name='cone',
            name='stime_bc',
        ),
        migrations.RemoveField(
            model_name='cone',
            name='stime_unc',
        ),
    ]
