# Generated by Django 2.0.5 on 2018-08-23 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20180823_0700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volume',
            old_name='value_mesured',
            new_name='value_measured',
        ),
    ]
