# Generated by Django 2.0.5 on 2018-08-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20180823_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='com',
            field=models.CharField(max_length=255, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='loaddate',
            field=models.DateTimeField(null=True, verbose_name='Load date, the date the data was entered (in UTC)'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='pubdate',
            field=models.DateTimeField(null=True, verbose_name='Publish date, the date the data become public'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='value_calculated',
            field=models.FloatField(null=True, verbose_name='value calculated'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='value_measured',
            field=models.FloatField(null=True, verbose_name='value measured'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='volume_method',
            field=models.CharField(choices=[('TOPO', 'Topographic'), ('TADRT', 'TADR Turin'), ('TADRC', 'TADR Clermont'), ('GAZ', 'Gaz')], max_length=5, null=True),
        ),
    ]
