# Generated by Django 2.0.5 on 2018-08-31 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20180823_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mntortho',
            old_name='geometry',
            new_name='raster',
        ),
        migrations.AlterField(
            model_name='fissure',
            name='com',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='fissure',
            name='com2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Comments2'),
        ),
        migrations.AlterField(
            model_name='fissure',
            name='com3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Comments3'),
        ),
        migrations.AlterField(
            model_name='fissure',
            name='com4',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Comments4'),
        ),
        migrations.AlterField(
            model_name='fissure',
            name='com5',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Comments5'),
        ),
        migrations.AlterField(
            model_name='fissure',
            name='com6',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Comments6'),
        ),
        migrations.AlterField(
            model_name='fissure',
            name='loaddate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Load date, the date the data was entered (in UTC)'),
        ),
        migrations.AlterField(
            model_name='fissure',
            name='opentime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Open time'),
        ),
        migrations.AlterField(
            model_name='fissure',
            name='opentime_bc',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year of open time before Christ'),
        ),
        migrations.AlterField(
            model_name='fissure',
            name='opentime_unc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Open time uncertainty'),
        ),
        migrations.AlterField(
            model_name='fissure',
            name='pubdate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Publish date, the date the data become public'),
        ),
    ]
