# Generated by Django 2.0.5 on 2018-09-03 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20180831_0530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eruption',
            name='geometry',
        ),
    ]
