# Generated by Django 2.0.5 on 2018-09-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_remove_eruption_geometry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cone',
            name='name',
            field=models.CharField(max_length=60, null=True, verbose_name='Cone Name'),
        ),
    ]
