# Generated by Django 2.0.5 on 2018-10-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20180903_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cone',
            name='accretion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of accretion'),
        ),
        migrations.AlterField(
            model_name='cone',
            name='accretion_date_bc',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year of accretion date before Christ'),
        ),
        migrations.AlterField(
            model_name='cone',
            name='accretion_date_unc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Accretion date uncertainty'),
        ),
        migrations.AlterField(
            model_name='cone',
            name='cone_type',
            field=models.CharField(blank=True, choices=[('STRAT', 'Stratocone'), ('SPATT', 'Spatter cone'), ('TUFFC', 'Tuff cones'), ('CINDE', 'Cinder cone'), ('ROOTL', 'Rootless cones')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='cone',
            name='crater_diameter',
            field=models.FloatField(blank=True, null=True, verbose_name='Crater diameter'),
        ),
        migrations.AlterField(
            model_name='cone',
            name='disappearance_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of disappearance'),
        ),
        migrations.AlterField(
            model_name='cone',
            name='disappearance_date_bc',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year of disappearance date before Christ'),
        ),
        migrations.AlterField(
            model_name='cone',
            name='disappearance_date_unc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Disappearance date uncertainty'),
        ),
        migrations.AlterField(
            model_name='cone',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='Height of the cone'),
        ),
        migrations.AlterField(
            model_name='cone',
            name='loaddate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Load date, the date the data was entered (in UTC)'),
        ),
        migrations.AlterField(
            model_name='cone',
            name='name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Cone Name'),
        ),
        migrations.AlterField(
            model_name='cone',
            name='pubdate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Publish date, the date the data become public'),
        ),
    ]
