# Generated by Django 2.0.5 on 2018-10-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20181001_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cone',
            name='cb_ids',
            field=models.ManyToManyField(blank=True, to='app.Bibliographic'),
        ),
    ]
