# Generated by Django 2.0.5 on 2018-10-01 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20181001_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cone',
            name='cc_load',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cone_cc_load_id', to='app.Contact'),
        ),
        migrations.AlterField(
            model_name='cone',
            name='cc_pub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cone_cc_pub_id', to='app.Contact'),
        ),
        migrations.AlterField(
            model_name='cone',
            name='fissure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cone_fissure_id', to='app.Fissure'),
        ),
    ]
