# Generated by Django 2.0.5 on 2018-10-01 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20181001_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fissure',
            name='cb_ids',
            field=models.ManyToManyField(blank=True, to='app.Bibliographic'),
        ),
        migrations.AlterField(
            model_name='fissure',
            name='cc_load',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fissure_cc_load_id', to='app.Contact'),
        ),
        migrations.AlterField(
            model_name='fissure',
            name='cc_pub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fissure_cc_pub_id', to='app.Contact'),
        ),
        migrations.AlterField(
            model_name='fissure',
            name='ed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fissure_ed_id', to='app.Eruption'),
        ),
    ]
