# Generated by Django 2.0.5 on 2018-10-02 05:52

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20181001_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mntortho',
            name='am',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mo_am_id', to='app.AcquisitionMethod'),
        ),
        migrations.AlterField(
            model_name='mntortho',
            name='cb_ids',
            field=models.ManyToManyField(blank=True, to='app.Bibliographic'),
        ),
        migrations.AlterField(
            model_name='mntortho',
            name='cc_load',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mo_cc_load_id', to='app.Contact'),
        ),
        migrations.AlterField(
            model_name='mntortho',
            name='cc_pub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mo_cc_pub_id', to='app.Contact'),
        ),
        migrations.AlterField(
            model_name='mntortho',
            name='flow_ids',
            field=models.ManyToManyField(blank=True, to='app.Flow'),
        ),
        migrations.AlterField(
            model_name='mntortho',
            name='gcp_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='Gcp number'),
        ),
        migrations.AlterField(
            model_name='mntortho',
            name='loaddate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Load date, the date the data was entered (in UTC)'),
        ),
        migrations.AlterField(
            model_name='mntortho',
            name='mo_gcp_type',
            field=models.CharField(blank=True, choices=[('GNSSM', 'GNSS measure'), ('RIMAG', 'Replicated image')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='mntortho',
            name='mo_software',
            field=models.CharField(blank=True, choices=[('PHOTO', 'PhotoScan'), ('MICMA', 'MicMac'), ('ERDAS', 'ERDAS'), ('ARCVI', 'ArcView'), ('POIVI', 'Poivillier'), ('ENVI', 'Envi'), ('GLOBM', 'Global Mapper'), ('CLOUD', 'Cloud Compare')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='mntortho',
            name='mo_type',
            field=models.CharField(blank=True, choices=[('MNT', 'Mnt'), ('ORTHO', 'Orthophoto')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='mntortho',
            name='precision',
            field=models.FloatField(blank=True, null=True, verbose_name='Accuracy of the reference altitude'),
        ),
        migrations.AlterField(
            model_name='mntortho',
            name='pubdate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Publish date, the date the data become public'),
        ),
        migrations.AlterField(
            model_name='mntortho',
            name='raster',
            field=django.contrib.gis.db.models.fields.RasterField(blank=True, null=True, srid=32740),
        ),
        migrations.AlterField(
            model_name='mntortho',
            name='reference_altitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Reference altitude'),
        ),
    ]
