# Generated by Django 2.0.5 on 2018-10-10 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20181002_0552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eruption',
            old_name='cc_load_id',
            new_name='cc_load',
        ),
        migrations.RenameField(
            model_name='seismicevent',
            old_name='cc_load_id',
            new_name='cc_load',
        ),
    ]
