# Generated by Django 2.0.5 on 2018-10-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_auto_20181010_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eruption',
            name='cb_ids',
            field=models.ManyToManyField(to='app.Bibliographic', verbose_name='Bibliographic reference'),
        ),
    ]
