# Generated by Django 2.0.5 on 2018-10-10 10:26

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_auto_20181010_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisitionmethod',
            name='cb_ids',
            field=models.ManyToManyField(to='app.Bibliographic', verbose_name='Bibliographic reference'),
        ),
        migrations.AlterField(
            model_name='acquisitiontool',
            name='am_ids',
            field=models.ManyToManyField(to='app.AcquisitionMethod', verbose_name='Acquisition method'),
        ),
        migrations.AlterField(
            model_name='acquisitiontool',
            name='cb_ids',
            field=models.ManyToManyField(to='app.Bibliographic', verbose_name='Bibliographic reference'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='cb_ids',
            field=models.ManyToManyField(to='app.Bibliographic', verbose_name='Bibliographic reference'),
        ),
        migrations.AlterField(
            model_name='cone',
            name='cb_ids',
            field=models.ManyToManyField(blank=True, to='app.Bibliographic', verbose_name='Bibliographic reference'),
        ),
        migrations.AlterField(
            model_name='eruptionobservation',
            name='cb_ids',
            field=models.ManyToManyField(to='app.Bibliographic', verbose_name='Bibliographic reference'),
        ),
        migrations.AlterField(
            model_name='fissure',
            name='cb_ids',
            field=models.ManyToManyField(blank=True, to='app.Bibliographic', verbose_name='Bibliographic reference'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='cb_ids',
            field=models.ManyToManyField(to='app.Bibliographic', verbose_name='Bibliographic reference'),
        ),
        migrations.AlterField(
            model_name='mntortho',
            name='cb_ids',
            field=models.ManyToManyField(blank=True, to='app.Bibliographic', verbose_name='Bibliographic reference'),
        ),
        migrations.AlterField(
            model_name='mntortho',
            name='flow_ids',
            field=models.ManyToManyField(blank=True, to='app.Flow', verbose_name='Related flows'),
        ),
        migrations.AlterField(
            model_name='mntortho',
            name='raster',
            field=django.contrib.gis.db.models.fields.RasterField(blank=True, null=True, srid=32740, verbose_name='Related raster'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='cb_ids',
            field=models.ManyToManyField(to='app.Bibliographic', verbose_name='Bibliographic reference'),
        ),
        migrations.AlterField(
            model_name='petrology',
            name='cb_ids',
            field=models.ManyToManyField(to='app.Bibliographic', verbose_name='Bibliographic reference'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='cb_ids',
            field=models.ManyToManyField(to='app.Bibliographic', verbose_name='Bibliographic reference'),
        ),
        migrations.AlterField(
            model_name='satelliteairplane',
            name='cb_ids',
            field=models.ManyToManyField(to='app.Bibliographic', verbose_name='Bibliographic reference'),
        ),
        migrations.AlterField(
            model_name='seismicevent',
            name='cb_ids',
            field=models.ManyToManyField(to='app.Bibliographic', verbose_name='Bibliographic reference'),
        ),
        migrations.AlterField(
            model_name='tephras',
            name='cb_ids',
            field=models.ManyToManyField(to='app.Bibliographic', verbose_name='Bibliographic reference'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='cb_ids',
            field=models.ManyToManyField(to='app.Bibliographic', verbose_name='Bibliographic reference'),
        ),
    ]
