# Generated by Django 2.0.5 on 2018-10-26 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20181010_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibliographic',
            name='cc_load',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cb_cc_load_id', to='app.Contact', verbose_name='Loading contact'),
        ),
        migrations.AlterField(
            model_name='volcano',
            name='cc_load',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vd_cc_load_id', to='app.Contact', verbose_name='Loading contact'),
        ),
    ]
