# Generated by Django 2.0.5 on 2018-10-26 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_auto_20181026_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisitionmethod',
            name='cc_load',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='am_cc_load_id', to='app.Contact', verbose_name='Loading contact'),
        ),
        migrations.AlterField(
            model_name='acquisitionmethod',
            name='cc_pub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='am_cc_pub_id', to='app.Contact', verbose_name='Contact that published the data'),
        ),
        migrations.AlterField(
            model_name='acquisitionmethod',
            name='cs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='am_cs_id', to='app.SatelliteAirplane', verbose_name='Related satellite/ airplane'),
        ),
        migrations.AlterField(
            model_name='acquisitiontool',
            name='cc_load',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='at_cc_load_id', to='app.Contact', verbose_name='Loading contact'),
        ),
        migrations.AlterField(
            model_name='acquisitiontool',
            name='cc_pub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='at_cc_pub_id', to='app.Contact', verbose_name='Contact that published the data'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='cc_load',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compo_cc_load_id', to='app.Contact', verbose_name='Loading contact'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='cc_pub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compo_cc_pub_id', to='app.Contact', verbose_name='Contact that published the data'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compo_sample_id', to='app.Sample', verbose_name='Related sample'),
        ),
        migrations.AlterField(
            model_name='cone',
            name='cc_load',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cone_cc_load_id', to='app.Contact', verbose_name='Loading contact'),
        ),
        migrations.AlterField(
            model_name='cone',
            name='cc_pub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cone_cc_pub_id', to='app.Contact', verbose_name='Contact that published the data'),
        ),
        migrations.AlterField(
            model_name='cone',
            name='fissure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cone_fissure_id', to='app.Fissure', verbose_name='Related fissure'),
        ),
        migrations.AlterField(
            model_name='eruption',
            name='cc_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ed_cc_id', to='app.Contact', verbose_name='First contact'),
        ),
        migrations.AlterField(
            model_name='eruption',
            name='cc_id2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ed_cc_id2', to='app.Contact', verbose_name='Second contact'),
        ),
        migrations.AlterField(
            model_name='eruption',
            name='cc_id3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ed_cc_id3', to='app.Contact', verbose_name='Third contact'),
        ),
        migrations.AlterField(
            model_name='eruption',
            name='cc_load',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ed_cc_load_id', to='app.Contact', verbose_name='Loading contact'),
        ),
        migrations.AlterField(
            model_name='eruption',
            name='vd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ed_vd_id', to='app.Volcano', verbose_name='Related volcano'),
        ),
        migrations.AlterField(
            model_name='eruptionobservation',
            name='cc_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eo_cc_id', to='app.Contact', verbose_name='First contact'),
        ),
        migrations.AlterField(
            model_name='eruptionobservation',
            name='cc_id2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eo_cc_id2', to='app.Contact', verbose_name='Second contact'),
        ),
        migrations.AlterField(
            model_name='eruptionobservation',
            name='cc_id3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eo_cc_id3', to='app.Contact', verbose_name='Third contact'),
        ),
        migrations.AlterField(
            model_name='eruptionobservation',
            name='cc_id4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eo_cc_id4', to='app.Contact', verbose_name='Fourth contact'),
        ),
        migrations.AlterField(
            model_name='eruptionobservation',
            name='cc_id5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eo_cc_id5', to='app.Contact', verbose_name='Fith contact'),
        ),
        migrations.AlterField(
            model_name='eruptionobservation',
            name='cc_load',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eo_cc_load_id', to='app.Contact', verbose_name='Loading contact'),
        ),
        migrations.AlterField(
            model_name='fissure',
            name='cc_load',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fissure_cc_load_id', to='app.Contact', verbose_name='Loading contact'),
        ),
        migrations.AlterField(
            model_name='fissure',
            name='cc_pub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fissure_cc_pub_id', to='app.Contact', verbose_name='Contact taht published the data'),
        ),
        migrations.AlterField(
            model_name='fissure',
            name='ed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fissure_ed_id', to='app.Eruption', verbose_name='Related eruption'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='cc_load',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flow_cc_load_id', to='app.Contact', verbose_name='Loading contact'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='cc_pub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flow_cc_pub_id', to='app.Contact', verbose_name='Contact that published the data'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='fissure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flow_fissure_id', to='app.Fissure', verbose_name='Related fissure'),
        ),
        migrations.AlterField(
            model_name='mntortho',
            name='am',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mo_am_id', to='app.AcquisitionMethod', verbose_name='Acquisition method'),
        ),
        migrations.AlterField(
            model_name='mntortho',
            name='cc_load',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mo_cc_load_id', to='app.Contact', verbose_name='Loading contact'),
        ),
        migrations.AlterField(
            model_name='mntortho',
            name='cc_pub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mo_cc_pub_id', to='app.Contact', verbose_name='Contact that published the data'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='cc_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_cc_id', to='app.Contact', verbose_name='First contact'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='cc_id2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_cc_id2', to='app.Contact', verbose_name='Second contact'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='cc_id3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_cc_id3', to='app.Contact', verbose_name='Third contact'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='cc_id4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_cc_id4', to='app.Contact', verbose_name='Fourth contact'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='cc_id5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_cc_id5', to='app.Contact', verbose_name='Fith contact'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='cc_load',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_cc_load_id', to='app.Contact', verbose_name='Loading contact'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='vd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_vd_id', to='app.Volcano', verbose_name='Related volcano'),
        ),
        migrations.AlterField(
            model_name='petrology',
            name='cc_load',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='petro_cc_load_id', to='app.Contact', verbose_name='Loading contact'),
        ),
        migrations.AlterField(
            model_name='petrology',
            name='cc_pub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='petro_cc_pub_id', to='app.Contact', verbose_name='Contact that published the data'),
        ),
        migrations.AlterField(
            model_name='petrology',
            name='sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='petro_sample_id', to='app.Sample', verbose_name='Related sample'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='cc_load',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sample_cc_load_id', to='app.Contact', verbose_name='Loading contact'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='cc_pub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sample_cc_pub_id', to='app.Contact', verbose_name='Contact that published the data'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='cone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sample_cone_id', to='app.Cone', verbose_name='Related cone'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='flow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sample_flow_id', to='app.Flow', verbose_name='Related flow'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='teph',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sample_teph_id', to='app.Tephras', verbose_name='Related tephras'),
        ),
        migrations.AlterField(
            model_name='satelliteairplane',
            name='cc_load',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cs_cc_load_id', to='app.Contact', verbose_name='Loading contact'),
        ),
        migrations.AlterField(
            model_name='satelliteairplane',
            name='cc_pub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cs_cc_pub_id', to='app.Contact', verbose_name='Contact that published the data'),
        ),
        migrations.AlterField(
            model_name='seismicevent',
            name='cc_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sd_ev_cc_id', to='app.Contact', verbose_name='First contact'),
        ),
        migrations.AlterField(
            model_name='seismicevent',
            name='cc_id2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sd_ev_cc_id2', to='app.Contact', verbose_name='Second contact'),
        ),
        migrations.AlterField(
            model_name='seismicevent',
            name='cc_id3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sd_ev_cc_id3', to='app.Contact', verbose_name='Third contact'),
        ),
        migrations.AlterField(
            model_name='seismicevent',
            name='cc_load',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sd_ev_cc_load_id', to='app.Contact', verbose_name='Loading contact'),
        ),
        migrations.AlterField(
            model_name='tephras',
            name='cc_load',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teph_cc_load_id', to='app.Contact', verbose_name='Loading contact'),
        ),
        migrations.AlterField(
            model_name='tephras',
            name='cc_pub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teph_cc_pub_id', to='app.Contact', verbose_name='Contact that published the data'),
        ),
        migrations.AlterField(
            model_name='tephras',
            name='fissure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teph_fissure_id', to='app.Fissure', verbose_name='Related fissure'),
        ),
        migrations.AlterField(
            model_name='volcano',
            name='cc_id1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vd_cc_id1', to='app.Contact', verbose_name='First contact'),
        ),
        migrations.AlterField(
            model_name='volcano',
            name='cc_id2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vd_cc_id2', to='app.Contact', verbose_name='Second contact'),
        ),
        migrations.AlterField(
            model_name='volcano',
            name='cc_id3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vd_cc_id3', to='app.Contact', verbose_name='Third contact'),
        ),
        migrations.AlterField(
            model_name='volcano',
            name='cc_id4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vd_cc_id4', to='app.Contact', verbose_name='Fourth contact'),
        ),
        migrations.AlterField(
            model_name='volcano',
            name='cc_id5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vd_cc_id5', to='app.Contact', verbose_name='Fith contact'),
        ),
        migrations.AlterField(
            model_name='volcanoinformation',
            name='cc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vd_inf_cc_id', to='app.Contact', verbose_name='First contact'),
        ),
        migrations.AlterField(
            model_name='volcanoinformation',
            name='cc_load',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vd_inf_cc_load_id', to='app.Contact', verbose_name='Loading contact'),
        ),
        migrations.AlterField(
            model_name='volcanoinformation',
            name='vd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vd_inf_vd_id', to='app.Volcano', verbose_name='Related volcano'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='cc_load',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volume_cc_load_id', to='app.Contact', verbose_name='Loading contact'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='cc_pub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volume_cc_pub_id', to='app.Contact', verbose_name='Contact that published the data'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='cone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volume_cone_id', to='app.Cone', verbose_name='Related cone'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volume_flow_id', to='app.Flow', verbose_name='Related flow'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='teph',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volume_teph_id', to='app.Tephras', verbose_name='Related tephras'),
        ),
    ]
